---
- hosts: device
  tasks:
    - name: Install packages
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - PyYAML
          - bash
          - bc
          - bind-utils
          - boost-devel
          - bzip2
          - centos-release-scl
          - clang-devel
          - cmake
          - coreutils
          - cpio
          - createrepo
          - curl
          - deltarpm
          - dmidecode
          - enscript
          - ethtool
          - gawk
          - gcc
          - gcc-c++
          - git
          - glib2-devel
          - grep
          - gzip
          - iotop
          - iperf3
          - java-1.8.0-openjdk
          - java-1.8.0-openjdk-devel
          - ksh
          - less
          - lftp
          - lsof
          - make
          - mlocate
          - net-tools
          - nmap
          - ntp
          - openssh
          - openssl
          - parted
          - perl
          - perltidy
          - procps-ng
          - python
          - python-jinja2
          - python-requests
          - python-six
          - redhat-lsb
          - rpm-build
          - rpmlint
          - rsync
          - ruby
          - ruby-irb
          - screen
          - sed
          - strace
          - subversion
          - sudo
          - tar
          - tcpdump
          - tmux
          - vim-enhanced
          - wget
          - xz
          - yum-cron
          - zsh
    - name: Enable/start services
      service:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - crond
        - ntpd
        - rsyslog
        - sshd
        - yum-cron
    - name: Add SCL repository
      yum_repository:
        name: scl
        description: SCL YUM repo
        baseurl: http://mirror.centos.org/centos-$releasever/$releasever/sclo/$basearch/rh/
    - name: Install SCL packages
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - devtoolset-8
    - name: Add EPEL repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
        gpgkey: https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
    - name: Install EPEL packages
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - fping
          - golang
          - htop
          - ninja-build
          - pychecker
          - python2-pip
          - python-psutil
