---
- hosts: device
  tasks:
    - name: Install packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - ant
          - atop
          - awscli
          - bash
          - black
          - build-essential
          - bzip2
          - clang
          - clang-format
          - cmake
          - coreutils
          - cpio
          - curl
          - cython
          - dmidecode
          - dnsutils
          - dos2unix
          - enscript
          - flake8
          - fping
          - gawk
          - git
          - golang
          - grep
          - gzip
          - htop
          - hwloc
          - iftop
          - iotop
          - ipython
          - ksh
          - less
          - lftp
          - libboost-all-dev
          - libglib2.0-dev
          - libkeyutils-dev
          - libpcap-dev
          - libperl-critic-perl
          - librpm-dev
          - libssl-dev
          - libsystemd-dev
          - lsof
          - make
          - mlocate
          - net-tools
          - ninja-build
          - nmap
          - ntp
          - openjdk-11-jdk
          - openssh-client
          - openssh-server
          - openssl
          - p7zip-full
          - parted
          - pbzip2
          - pep8
          - perl
          - perltidy
          - pigz
          - pixz
          - procps
          - pychecker
          - pyflakes
          - pylint
          - pylint3
          - python
          - python-boto
          - python-boto3
          - python-jinja2
          - python-nose
          - python-pip
          - python-psutil
          - python-requests
          - python-six
          - python-virtualenv
          - python-yaml
          - python3-boto
          - python3-boto3
          - python3-jinja2
          - python3-nose
          - python3-pip
          - python3-psutil
          - python3-pytest
          - python3-requests
          - python3-six
          - python3-virtualenv
          - python3-yaml
          - rsync
          - ruby
          - screen
          - sed
          - silversearcher-ag
          - strace
          - subversion
          - sudo
          - tar
          - tcpdump
          - tmux
          - vim-nox
          - wget
          - xz-utils
          - yapf3
          - zsh
    - name: Enable/start services
      service:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - cron
        - ntp
        - rsyslog
        - ssh
