---
- hosts: device
  tasks:
    - name: Install packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - aptitude
          - bash
          - build-essential
          - bzip2
          - clang
          - clang-format
          - cmake
          - coreutils
          - cpio
          - curl
          - dmidecode
          - dnsutils
          - dos2unix
          - fping
          - gawk
          - git
          - golang
          - grep
          - gzip
          - htop
          - hwloc
          - less
          - lsof
          - make
          - mlocate
          - net-tools
          - ninja-build
          - nmap
          - ntp
          - openjdk-17-jdk
          - openssh-client
          - openssh-server
          - openssl
          - p7zip-full
          - parted
          - pbzip2
          - perl
          - perltidy
          - pigz
          - pixz
          - procps
          - python3
          - python3-boto
          - python3-boto3
          - python3-jinja2
          - python3-nose
          - python3-pip
          - python3-psutil
          - python3-pytest
          - python3-requests
          - python3-six
          - python3-virtualenv
          - python3-yaml
          - ripgrep
          - rsync
          - ruby
          - screen
          - sed
          - silversearcher-ag
          - strace
          - sudo
          - tar
          - tcpdump
          - tmux
          - vim-nox
          - wget
          - xz-utils
          - zsh
    - name: Enable/start services
      service:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - cron
        - ntp
        - ssh
        - systemd-journald
