---
- hosts: device
  tasks:
    - name: Install packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - build-essential
          - cmake
          - exploitdb
          - fping
          - git
          - gobuster
          - masscan
          - nmap
          - openssh-server
          - rsync
          - tcpdump
          - vim-nox
          - wordlists
    - name: Enable/start services
      service:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - ssh
