---
- hosts: device
  tasks:
    - name: Install packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - alacritty
          - cheese
          - handbrake
          - keepassxc
          - sound-juicer
