---
- hosts: device
  tasks:
    # powershell is not available on aarch64.
    # It looks like it is only on x86_64.
    - name: Install powershell
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - powershell
      when: ansible_architecture == "x86_64"
    - name: Install packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - acpi
          - alsa-utils
          - arp-scan
          - black
          - btop
          - build-essential
          - cmake
          - curl
          - exploitdb
          - fd-find
          - flake8
          - fping
          - git
          - gobuster
          - hashcat
          - htop
          - iperf3
          - iputils-ping
          - john
          - libssl-dev
          - locate
          - masscan
          - ncdu
          - netcat-traditional
          - ninja-build
          - nmap
          - openssh-server
          - pkg-config
          - poppler-utils
          - pylint
          - python3-boto3
          - python3-dateutil
          - python3-flake8
          - python3-jinja2
          - python3-packaging
          - python3-pip
          - python3-psutil
          - python3-pytest
          - python3-requests
          - python3-six
          - python3-venv
          - python3-yaml
          - ripgrep
          - rsync
          - screen
          - seclists
          - silversearcher-ag
          - tcpdump
          - tmux
          - vim-nox
          - whois
          - wordlists
          - zsh
    - name: Enable/start services
      service:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - ssh
