---
- hosts: device
  tasks:
    - name: Install packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - arp-scan
          - black
          - build-essential
          - cmake
          - curl
          - exploitdb
          - fcrackzip
          - ffmpeg
          - flake8
          - fping
          - git
          - gobuster
          - hashcat
          - iperf3
          - iputils-ping
          - john
          - libssl-dev
          - locate
          - masscan
          - netcat-openbsd
          - nmap
          - openssh-server
          - pkg-config
          - powershell
          - pylint
          - python3-boto3
          - python3-dateutil
          - python3-flake8
          - python3-jinja2
          - python3-packaging
          - python3-pip
          - python3-psutil
          - python3-pytest
          - python3-requests
          - python3-six
          - python3-venv
          - python3-yaml
          - rsync
          - screen
          - tcpdump
          - tmux
          - vim-nox
          - wordlists
          - zsh
    - name: Enable/start services
      service:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - ssh
