---
- hosts: device
  tasks:
    - name: Install packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - cheese
          - gnome-tweaks
          - handbrake
          - keepassxc
          - remmina
          - rhythmbox
          - sound-juicer
