---
- hosts: device
  tasks:
    - name: Install snaps
      snap:
        name: "{{ packages }}"
        classic: true
      vars:
        packages:
          - clion
          - datagrip
          - goland
          - pycharm-professional
          - rustrover
    - name: Install beta snaps with the classic confinement
      snap:
        name: "{{ packages }}"
        channel: beta
        classic: yes
      vars:
        packages:
          - zig
