---
- hosts: device
  tasks:
    - name: Install amd64-only stable snaps with the classic confinement
      snap:
        name: "{{ packages }}"
        channel: stable
        classic: yes
      when: ansible_architecture == "x86_64"
      vars:
        packages:
          - claude-code
          - gemini-cli
    - name: Install other stable snaps with the classic confinement
      snap:
        name: "{{ packages }}"
        channel: stable
        classic: yes
      vars:
        packages:
          - chromium
          - ghostty
          - gopls
          - helix
          - nvim
    - name: Install beta snaps with the classic confinement
      snap:
        name: "{{ packages }}"
        channel: beta
        classic: yes
      vars:
        packages:
          - zig
