---
- hosts: device
  tasks:
    - name: Install packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - awesome
          - awesome-doc
          - awesome-extra
          - gnome-tweaks
          - handbrake
          - keepassxc
          - qtcreator
          - sound-juicer
