---
- hosts: device
  tasks:
    - name: Install the NVIDIA CUDA keyring package
      apt:
        deb: "https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb"
    - name: Update the apt cache after adding the CUDA repo
      apt:
        update_cache: yes
    - name: Install packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - build-essential
          - cmake
          - cuda-toolkit
          - git
          - libfreeimage-dev
          - libglut-dev
          - libvulkan-dev
          - ninja-build
          - nvtop
