---
- hosts: device
  tasks:
    - name: Install packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - acpi
          - arp-scan
          - atop
          - b3sum
          - bash
          - bc
          - black
          - btop
          - build-essential
          - bzip2
          - cifs-utils
          - clang
          - clang-format
          - clang-tidy
          - clang-tools
          - cmake
          - coreutils
          - cpio
          - curl
          - cython3
          - dmidecode
          - dnsutils
          - dos2unix
          - enscript
          - ethtool
          - ffmpeg
          - flake8
          - fping
          - fzf
          - gawk
          - git
          - gobuster
          - golang
          - grep
          - gzip
          - htop
          - hwinfo
          - hwloc
          - iftop
          - inxi
          - iotop
          - iperf3
          - ipython3
          - kitty
          - ksh
          - less
          - lftp
          - libboost-all-dev
          - libbz2-dev
          - libcdio-utils
          - libffi-dev
          - libglib2.0-dev
          - libkeyutils-dev
          - liblzma-dev
          - libncursesw5-dev
          - libpcap-dev
          - libperl-critic-perl
          - libreadline-dev
          - librpm-dev
          - libsqlite3-dev
          - libssl-dev
          - libsystemd-dev
          - libuv1-dev
          - libxml2-dev
          - libxmlsec1-dev
          - llvm
          - lsof
          - make
          - mtr
          - mutt
          - ncdu
          - net-tools
          - ninja-build
          - nmap
          - ntp
          - openssh-client
          - openssh-server
          - openssl
          - p7zip-full
          - pandoc
          - parted
          - pbzip2
          - perl
          - perltidy
          - pigz
          - pipenv
          - pkg-config
          - plocate
          - poppler-utils
          - procps
          - psmisc
          - pyflakes3
          - pylint
          - python3-boto
          - python3-boto3
          - python3-jinja2
          - python3-nose
          - python3-packaging
          - python3-pep8
          - python3-pip
          - python3-psutil
          - python3-pytest
          - python3-requests
          - python3-six
          - python3-venv
          - python3-virtualenv
          - python3-yaml
          - qtbase5-dev
          - ranger
          - rsync
          - rtorrent
          - ruby
          - s4cmd
          - screen
          - sed
          - shellcheck
          - shfmt
          - silversearcher-ag
          - sshpass
          - strace
          - subversion
          - sudo
          - sysstat
          - tar
          - tcpdump
          - tcptraceroute
          - texlive-xetex
          - tk-dev
          - tmux
          - vim-nox
          - vorbis-tools
          - w3m
          - wavemon
          - weechat
          - wget
          - whois
          - xxhash
          - xz-utils
          - yamllint
          - yapf3
          - zlib1g-dev
          - zsh
          - zstd
          - zsync
    - name: Enable/start services
      service:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - cron
        - ntp
        - rsyslog
        - ssh
        - sysstat
